
project_id = "test"
[functions.scrape-jigsaw]
verify_jwt = false
[functions.schedule-events-update]
verify_jwt = false
[functions.chat]
verify_jwt = false
[functions.scrape-pacha]
verify_jwt = false
